// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZZWSNseoO8zF0taZvwvnX5UuxsH4kGjo',
    appId: '1:211248936521:web:69ffd7eb3bd99c24d0f198',
    messagingSenderId: '211248936521',
    projectId: 'education-4919d',
    authDomain: 'education-4919d.firebaseapp.com',
    storageBucket: 'education-4919d.firebasestorage.app',
    measurementId: 'G-FKWJG359D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6t207EO8HIUXm3ivreKBf1c1AtBx-gg',
    appId: '1:211248936521:android:350f9d7d92f0c273d0f198',
    messagingSenderId: '211248936521',
    projectId: 'education-4919d',
    storageBucket: 'education-4919d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlizAWUgEN4CsWBH82Y20fjF9r70FlbHI',
    appId: '1:211248936521:ios:edb37dd606e0c6cdd0f198',
    messagingSenderId: '211248936521',
    projectId: 'education-4919d',
    storageBucket: 'education-4919d.firebasestorage.app',
    iosClientId: '211248936521-38u11dcbqor1ft3tc8j5iiu7l7b0h7k4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduspark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZZWSNseoO8zF0taZvwvnX5UuxsH4kGjo',
    appId: '1:211248936521:web:8d6585a58d6ca852d0f198',
    messagingSenderId: '211248936521',
    projectId: 'education-4919d',
    authDomain: 'education-4919d.firebaseapp.com',
    storageBucket: 'education-4919d.firebasestorage.app',
    measurementId: 'G-LGDLTC5S0C',
  );

}